CREATE DATABASE social_db;
USE social_db;
CREATE TABLE users (id INT AUTO_INCREMENT, name VARCHAR(100), email VARCHAR(100), password VARCHAR(100), PRIMARY KEY(id));
CREATE TABLE content (id INT AUTO_INCREMENT, subject VARCHAR(100), body VARCHAR(8000), date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, likes INT, author_id INT, PRIMARY KEY(id));
CREATE TABLE comments (id INT AUTO_INCREMENT, body VARCHAR(1000), date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, likes INT, author_id INT, content_id INT, PRIMARY KEY(id));